version: '3.8'

services:
  # Nginx 反向代理 (管理端)
  nginx-admin:
    image: nginx:alpine
    container_name: panda-quant-nginx-admin
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/admin.nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/admin.conf.d:/etc/nginx/conf.d:ro
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/www:/var/www/certbot
    networks:
      - panda-quant-network
    depends_on:
      - admin-api
      - admin-ui
    restart: unless-stopped

  # Certbot 用于 SSL 证书
  certbot-admin:
    image: certbot/certbot
    container_name: panda-quant-certbot-admin
    volumes:
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/www:/var/www/certbot
    networks:
      - panda-quant-network
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  # MongoDB 数据库
  mongodb:
    image: mongo:4.4
    container_name: panda-quant-mongodb
    ports:
      - "${DB_PORT}:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - panda-quant-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis 缓存
  redis:
    image: redis:6.0
    container_name: panda-quant-redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - panda-quant-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 管理前端
  admin-ui:
    build:
      context: ./admin-ui
      dockerfile: Dockerfile
    container_name: panda-quant-admin-ui
    ports:
      - "3002:80"
    environment:
      - VITE_API_URL=https://admin-api.pandatrade.space
    depends_on:
      admin-api:
        condition: service_healthy
    networks:
      - panda-quant-network
    restart: unless-stopped

  # 管理后端
  admin-api:
    build:
      context: ./admin-api
      dockerfile: Dockerfile
    container_name: panda-quant-admin-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://${DB_USER}:${DB_PASSWORD}@mongodb:27017/panda-quant
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=24h
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - panda-quant-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  panda-quant-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
  nginx_letsencrypt:
  nginx_www: 