version: '3.8'

services:
  # MongoDB 数据库
  mongodb:
    image: mongo:6.0
    container_name: panda-quant-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - panda-quant-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis 缓存
  redis:
    image: redis:7.0-alpine
    container_name: panda-quant-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - panda-quant-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx 反向代理 (用户端)
  nginx-user:
    image: nginx:alpine
    container_name: panda-quant-nginx-user
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/user.nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/user.conf.d:/etc/nginx/conf.d:ro
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/www:/var/www/certbot
    networks:
      - panda-quant-network
    depends_on:
      - user-api
      - user-ui
    restart: unless-stopped

  # Certbot 用于 SSL 证书
  certbot-user:
    image: certbot/certbot
    container_name: panda-quant-certbot-user
    volumes:
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/www:/var/www/certbot
    networks:
      - panda-quant-network
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  # 用户前端
  user-ui:
    build:
      context: ./user-ui
      dockerfile: Dockerfile
    container_name: panda-quant-user-ui
    ports:
      - "3003:80"
    environment:
      - VITE_API_URL=https://api.pandatrade.space
    depends_on:
      user-api:
        condition: service_healthy
    networks:
      - panda-quant-network
    restart: unless-stopped

  # 用户后端
  user-api:
    build:
      context: ./user-api
      dockerfile: Dockerfile
    container_name: panda-quant-user-api
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URI=mongodb://${DB_USER}:${DB_PASSWORD}@mongodb:27017/panda-quant
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=24h
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - panda-quant-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  panda-quant-network:
    driver: bridge

volumes:
  nginx_letsencrypt:
  nginx_www:
  mongodb_data:
  redis_data: 