[build]
builder = "nixpacks"
buildCommand = "npm run build:all"

[deploy]
startCommand = "npm run start:all"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production" 