version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    container_name: panda-quant-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/api
      - REDIS_URI=redis://redis:6379
    ports:
      - "4000:4000"
    depends_on:
      - mongo
      - redis
    networks:
      - user-network

  nginx-user:
    image: nginx:latest
    container_name: panda-quant-user-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/user.conf:/etc/nginx/conf.d/user.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - api
    networks:
      - user-network

  mongo:
    image: mongo:latest
    container_name: panda-quant-user-mongo
    restart: unless-stopped
    ports:
      - "27019:27017"
    volumes:
      - mongo_data:/data/db
    command: mongod --bind_ip_all
    networks:
      - user-network

  redis:
    image: redis:latest
    container_name: panda-quant-user-redis
    restart: unless-stopped
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    networks:
      - user-network

volumes:
  mongo_data:
    driver: local
  redis_data:
    driver: local

networks:
  user-network:
    driver: bridge