services:
  admin-api:
    build:
      context: ../admin-api
      dockerfile: ../docker/Dockerfile.admin-api
    container_name: panda-quant-admin-api
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/admin
      - REDIS_URI=redis://redis:6379
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    networks:
      - admin-network

  admin-ui:
    build:
      context: ../admin-ui
      dockerfile: ../docker/Dockerfile.admin-ui
      args:
        - NODE_ENV=production
    container_name: panda-quant-admin-ui
    restart: always
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
      - PORT=80
      - API_URL=http://admin-api:3000
    depends_on:
      - admin-api
    networks:
      - admin-network

  mongo:
    image: mongo:latest
    container_name: panda-quant-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - admin-network

  redis:
    image: redis:latest
    container_name: panda-quant-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - admin-network

networks:
  admin-network:
    driver: bridge

volumes:
  mongo_data:
  redis_data: 