version: '3.8'

services:
  user-ui:
    build:
      context: ..
      dockerfile: docker/Dockerfile.user-ui
    container_name: panda-quant-user-ui
    ports:
      - "8083:8083"
    restart: always
    networks:
      - panda-quant-network
    depends_on:
      - user-api
    user: "1000:1000"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

  user-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.user-api
    container_name: panda-quant-user-api
    ports:
      - "8082:8082"
    restart: always
    networks:
      - panda-quant-network
    environment:
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/admin
      - REDIS_URI=redis://:${REDIS_PASSWORD}@redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    depends_on:
      - mongodb
      - redis
    user: "1000:1000"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

networks:
  panda-quant-network:
    external: true 