version: '3.8'

services:
  strategy-engine:
    build:
      context: ..
      dockerfile: docker/Dockerfile.strategy-engine
    container_name: panda-quant-strategy-engine
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/strategy
      - REDIS_URI=redis://redis:6379
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
    networks:
      - default

  nginx-strategy:
    image: nginx:latest
    container_name: panda-quant-strategy-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/strategy-engine.nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - strategy-engine
    networks:
      - default

  mongo:
    image: mongo:latest
    container_name: panda-quant-strategy-mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - default

  redis:
    image: redis:latest
    container_name: panda-quant-strategy-redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - default

volumes:
  mongo_data:
  redis_data:

networks:
  default:
    name: docker_default 