version: '3.8'

services:
  user-ui:
    build:
      context: ..
      dockerfile: docker/Dockerfile.user-ui
    container_name: panda-quant-user-ui
    ports:
      - "3000:3000"
    restart: always
    networks:
      - panda-quant-network
    depends_on:
      - user-api
    user: "1000:1000"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

  user-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.user-api
    container_name: panda-quant-user-api
    ports:
      - "3001:3001"
    restart: always
    networks:
      - panda-quant-network
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/panda_quant?schema=public
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    user: "1000:1000"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

  postgres:
    image: postgres:15
    container_name: panda-quant-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=panda_quant
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - panda-quant-network
    restart: always

  redis:
    image: redis:7
    container_name: panda-quant-redis
    ports:
      - "6379:6379"
    networks:
      - panda-quant-network
    restart: always

networks:
  panda-quant-network:
    external: true

volumes:
  postgres_data: 