services:
  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile.server
    container_name: panda-quant-server
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 223.5.5.5
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGO_URI=mongodb://mongo:27017/strategy
      - REDIS_URI=redis://redis:6379
    ports:
      - "3001:3001"
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - strategy-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  strategy-engine:
    build:
      context: ..
      dockerfile: docker/Dockerfile.strategy-engine
    container_name: panda-quant-strategy-engine
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 223.5.5.5
    environment:
      - NODE_ENV=production
      - PORT=3003
      - MONGO_URI=mongodb://mongo:27017/strategy
      - REDIS_URI=redis://redis:6379
    ports:
      - "3003:3003"
    depends_on:
      server:
        condition: service_healthy
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - strategy-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx-strategy:
    image: nginx:latest
    container_name: panda-quant-strategy-nginx
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 223.5.5.5
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/server.nginx.conf:/etc/nginx/conf.d/server.conf
      - ./nginx/strategy-engine.nginx.conf:/etc/nginx/conf.d/strategy-engine.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/log/nginx:/var/log/nginx
    depends_on:
      server:
        condition: service_healthy
      strategy-engine:
        condition: service_healthy
    networks:
      - strategy-network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo:latest
    container_name: panda-quant-strategy-mongo
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 223.5.5.5
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    command: mongod --bind_ip_all
    networks:
      - strategy-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  redis:
    image: redis:latest
    container_name: panda-quant-strategy-redis
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 223.5.5.5
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - strategy-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mongo_data:
    driver: local
  redis_data:
    driver: local

networks:
  strategy-network:
    driver: bridge 