version: '3.8'

services:
  admin-ui:
    build:
      context: ..
      dockerfile: docker/Dockerfile.admin-ui
    container_name: panda-quant-admin-ui
    restart: always
    networks:
      - panda-quant-network
    depends_on:
      - admin-api

  admin-api:
    build:
      context: ../admin-api
      dockerfile: Dockerfile
    container_name: panda-quant-admin-api
    restart: always
    networks:
      - panda-quant-network
    environment:
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/admin
      - REDIS_URI=redis://:${REDIS_PASSWORD}@redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    container_name: panda-quant-mongodb
    restart: always
    networks:
      - panda-quant-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    container_name: panda-quant-redis
    restart: always
    networks:
      - panda-quant-network
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

networks:
  panda-quant-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data: 