version: '3.8'

services:
  admin-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.admin-api
    container_name: panda-quant-admin-api
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 223.5.5.5
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/admin
      - REDIS_URI=redis://redis:6379
    ports:
      - "4000:4000"
    depends_on:
      - mongo
      - redis
    networks:
      - admin-network

  admin-ui:
    build:
      context: ..
      dockerfile: docker/Dockerfile.admin-ui
    container_name: panda-quant-admin-ui
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 223.5.5.5
    environment:
      - NODE_ENV=production
      - PORT=3000
      - API_URL=http://admin-api:4000
    ports:
      - "3000:3000"
    depends_on:
      - admin-api
    networks:
      - admin-network

  nginx-admin:
    image: nginx:alpine
    container_name: panda-quant-admin-nginx
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 223.5.5.5
    ports:
      - "8080:80"
    volumes:
      - ./nginx/admin.nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../admin-ui/dist:/usr/share/nginx/html:ro
    depends_on:
      - admin-api
      - admin-ui
    networks:
      - admin-network

  mongo:
    image: mongo:latest
    container_name: panda-quant-admin-mongo
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 223.5.5.5
    ports:
      - "27019:27017"
    volumes:
      - mongo_data:/data/db
    command: mongod --bind_ip_all
    networks:
      - admin-network

  redis:
    image: redis:latest
    container_name: panda-quant-admin-redis
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 223.5.5.5
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    networks:
      - admin-network

volumes:
  mongo_data:
    driver: local
  redis_data:
    driver: local

networks:
  admin-network:
    driver: bridge 