services:
  user-api:
    build:
      context: ../user-api
      dockerfile: ../docker/Dockerfile.user-api
    container_name: panda-quant-user-api
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URI=mongodb://mongo:27017/user
      - REDIS_URI=redis://redis:6379
    ports:
      - "3001:3001"
    depends_on:
      - mongo
      - redis

  user-ui:
    build:
      context: ../user-ui
      dockerfile: ../docker/Dockerfile.user-ui
      args:
        - NODE_ENV=production
    container_name: panda-quant-user-ui
    restart: always
    ports:
      - "8082:80"
    environment:
      - NODE_ENV=production
      - PORT=80
      - API_URL=http://user-api:8083
    networks:
      - panda-quant-network
    depends_on:
      - user-api
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo:latest
    container_name: panda-quant-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: panda-quant-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:

networks:
  panda-quant-network:
    driver: bridge