version: '3.8'

services:
  user-ui:
    build:
      context: ../user-ui
      dockerfile: ../docker/Dockerfile.user-ui
      args:
        - NODE_ENV=production
        - SKIP_TYPE_CHECK=true
    container_name: panda-quant-user-ui
    restart: always
    ports:
      - "80:80"
    networks:
      - panda-quant-network
    depends_on:
      - user-api
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3

  user-api:
    build:
      context: ../user-api
      dockerfile: ../docker/Dockerfile.user-api
      args:
        - NODE_ENV=production
        - SKIP_TYPE_CHECK=true
    container_name: panda-quant-user-api
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URI=mongodb://admin:Wl528586*@mongodb:27017/admin
      - REDIS_URI=redis://:Wl528586*@redis:6380
      - POSTGRES_URI=postgresql://admin:Wl528586*@postgres:5432/panda_quant
    networks:
      - panda-quant-network
    depends_on:
      - mongodb
      - redis
      - postgres
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb:
    image: mongo:latest
    container_name: panda-quant-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Wl528586*
    volumes:
      - mongodb_data:/data/db
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:alpine
    container_name: panda-quant-redis
    restart: always
    ports:
      - "6380:6380"
    command: redis-server --port 6380 --requirepass Wl528586*
    volumes:
      - redis_data:/data
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6380", "-a", "Wl528586*", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:latest
    container_name: panda-quant-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Wl528586*
      - POSTGRES_DB=panda_quant
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d panda_quant"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  panda-quant-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
  postgres_data: