version: '3.8'

services:
  admin-ui:
    build:
      context: ../admin-ui
      dockerfile: Dockerfile
    container_name: panda-quant-admin-ui
    restart: always
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    networks:
      - panda-quant-network

  admin-api:
    build:
      context: ../admin-api
      dockerfile: Dockerfile
    container_name: panda-quant-admin-api
    restart: always
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    networks:
      - panda-quant-network
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    container_name: panda-quant-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - panda-quant-network

  redis:
    image: redis:latest
    container_name: panda-quant-redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - panda-quant-network

networks:
  panda-quant-network:
    external: true
    name: panda-quant-network

volumes:
  mongodb_data:
  redis_data: 