version: '3.8'

services:
  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile.server
    container_name: panda-quant-server
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 223.5.5.5
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/strategy
      - REDIS_URI=redis://redis:6379
    ports:
      - "4000:4000"
    depends_on:
      - mongo
      - redis
    networks:
      - strategy-network

  strategy-engine:
    build:
      context: ..
      dockerfile: docker/Dockerfile.strategy-engine
    container_name: panda-quant-strategy-engine
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 223.5.5.5
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/strategy
      - REDIS_URI=redis://redis:6379
    ports:
      - "3000:3000"
    depends_on:
      - server
      - mongo
      - redis
    networks:
      - strategy-network

  nginx-strategy:
    image: nginx:latest
    container_name: panda-quant-strategy-nginx
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 223.5.5.5
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/strategy.nginx.conf:/etc/nginx/conf.d/strategy.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - server
      - strategy-engine
    networks:
      - strategy-network

  mongo:
    image: mongo:latest
    container_name: panda-quant-strategy-mongo
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 223.5.5.5
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    command: mongod --bind_ip_all
    networks:
      - strategy-network

  redis:
    image: redis:latest
    container_name: panda-quant-strategy-redis
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 223.5.5.5
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - strategy-network

volumes:
  mongo_data:
    driver: local
  redis_data:
    driver: local

networks:
  strategy-network:
    driver: bridge 