services:
  admin-api:
    build:
      context: ../admin-api
      dockerfile: Dockerfile
    container_name: panda-quant-admin-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/admin
      - REDIS_URI=redis://redis:6379
      - JWT_SECRET=your_jwt_secret
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    networks:
      - admin-network

  admin-ui:
    build:
      context: ..
      dockerfile: docker/Dockerfile.admin-ui
    container_name: panda-quant-admin-ui
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:3000
    depends_on:
      - admin-api
    networks:
      - admin-network

  mongo:
    image: mongo:latest
    container_name: panda-quant-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: mongod --bind_ip_all --nojournal
    networks:
      - admin-network

  redis:
    image: redis:latest
    container_name: panda-quant-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - admin-network

networks:
  admin-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
  redis_data:
    driver: local 