services:
  strategy-engine:
    build:
      context: .
      dockerfile: Dockerfile.strategy-engine
    container_name: panda-quant-strategy-engine
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/strategy
      - REDIS_URI=redis://redis:6379
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis

  nginx-strategy:
    image: nginx:alpine
    container_name: panda-quant-strategy-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/strategy-engine.nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - strategy-engine

  mongo:
    image: mongo:latest
    container_name: panda-quant-strategy-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: panda-quant-strategy-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data: 