version: '3.8'

services:
  admin-ui:
    build:
      context: ../admin-ui
      dockerfile: ../docker/Dockerfile.admin-ui
      args:
        - NODE_ENV=production
        - SKIP_TYPE_CHECK=true
    container_name: panda-quant-admin-ui
    restart: always
    ports:
      - "80:80"
    networks:
      - panda-quant-network
    depends_on:
      - admin-api
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3

  admin-api:
    build:
      context: ../admin-api
      dockerfile: ../docker/Dockerfile.admin-api
      args:
        - NODE_ENV=production
        - SKIP_TYPE_CHECK=true
    container_name: panda-quant-admin-api
    restart: always
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - MONGODB_URI=mongodb://admin:Wl528586*@mongodb:27017/admin
      - REDIS_URI=redis://:Wl528586*@redis:6380
    networks:
      - panda-quant-network
    depends_on:
      - mongodb
      - redis
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb:
    image: mongo:latest
    container_name: panda-quant-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Wl528586*
    volumes:
      - mongodb_data:/data/db
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:alpine
    container_name: panda-quant-redis
    restart: always
    ports:
      - "6380:6380"
    command: redis-server --port 6380 --requirepass Wl528586*
    volumes:
      - redis_data:/data
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6380", "-a", "Wl528586*", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  panda-quant-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data: 