version: '3.8'

services:
  admin-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.admin-api
    container_name: panda-quant-admin-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/admin
      - REDIS_URI=redis://redis:6379
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    networks:
      - admin-network

  admin:
    build:
      context: ..
      dockerfile: docker/Dockerfile.admin
    container_name: panda-quant-admin
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
      - API_URL=https://admin-api.pandatrade.space
    ports:
      - "3001:3001"
    depends_on:
      - admin-api
    networks:
      - admin-network

  nginx-admin:
    image: nginx:latest
    container_name: panda-quant-admin-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/admin.nginx.conf:/etc/nginx/conf.d/admin.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - admin-api
      - admin
    networks:
      - admin-network

  mongo:
    image: mongo:latest
    container_name: panda-quant-admin-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: mongod --bind_ip_all
    networks:
      - admin-network

  redis:
    image: redis:latest
    container_name: panda-quant-admin-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - admin-network

volumes:
  mongo_data:
    driver: local
  redis_data:
    driver: local

networks:
  admin-network:
    driver: bridge 