version: '3.8'

services:
  admin-ui:
    build:
      context: ../admin-ui
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - SKIP_TYPE_CHECK=true
    container_name: panda-quant-admin-ui
    restart: always
    ports:
      - "8080:80"
    env_file:
      - .env
    networks:
      - panda-quant-network
    depends_on:
      - admin-api
    deploy:
      resources:
        limits:
          memory: 2G
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  admin-api:
    build:
      context: ../admin-api
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - SKIP_TYPE_CHECK=true
    container_name: panda-quant-admin-api
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
      - panda-quant-network
    depends_on:
      - mongodb
      - redis
    deploy:
      resources:
        limits:
          memory: 4G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb:
    image: mongo:latest
    container_name: panda-quant-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - panda-quant-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:alpine
    container_name: panda-quant-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - panda-quant-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  panda-quant-network:
    external: true
    name: panda-quant-network

volumes:
  mongodb_data:
  redis_data: 