services:
  user-api:
    build:
      context: ../user-api
      dockerfile: ../docker/Dockerfile.user-api
    container_name: panda-quant-user-api
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URI=mongodb://mongo:27018/user
      - REDIS_URI=redis://redis:6380
    ports:
      - "3001:3001"
    depends_on:
      - mongo
      - redis
    networks:
      - docker_user-network

  user-ui:
    build:
      context: ../user-ui
      dockerfile: ../docker/Dockerfile.user-ui
      args:
        - NODE_ENV=production
    container_name: panda-quant-user-ui
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - API_URL=http://user-api:3001
    networks:
      - docker_user-network
    depends_on:
      - user-api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo:latest
    container_name: panda-quant-user-mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - docker_user-network

  redis:
    image: redis:latest
    container_name: panda-quant-user-redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - docker_user-network

volumes:
  mongo_data:
  redis_data:

networks:
  docker_user-network:
    driver: bridge