services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.user-api
    container_name: panda-quant-api
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 223.5.5.5
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/api
      - REDIS_URI=redis://redis:6379
    ports:
      - "4000:4000"
    depends_on:
      - mongo
      - redis
    networks:
      - user-network

  ui:
    build:
      context: ..
      dockerfile: docker/Dockerfile.user-ui
    container_name: panda-quant-ui
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 223.5.5.5
    environment:
      - NODE_ENV=production
      - PORT=80
      - API_URL=http://api.pandatrade.space
      - NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID=e14194185b098392e41c394ac25a74a6
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - user-network

  mongo:
    image: mongo:latest
    container_name: panda-quant-user-mongo
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 223.5.5.5
    ports:
      - "27020:27017"
    volumes:
      - mongo_data:/data/db
    command: mongod --bind_ip_all
    networks:
      - user-network

  redis:
    image: redis:latest
    container_name: panda-quant-user-redis
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 223.5.5.5
    ports:
      - "6382:6379"
    volumes:
      - redis_data:/data
    networks:
      - user-network

volumes:
  mongo_data:
    driver: local
  redis_data:
    driver: local

networks:
  user-network:
    driver: bridge