version: '3.8'

services:
  strategy-engine:
    build:
      context: ..
      dockerfile: docker/Dockerfile.strategy-engine
    container_name: panda-quant-strategy-engine
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/strategy
      - REDIS_URI=redis://redis:6379
    ports:
      - "4000:4000"
    depends_on:
      - mongo
      - redis
    networks:
      - strategy-network

  nginx-strategy:
    image: nginx:latest
    container_name: panda-quant-strategy-nginx
    restart: unless-stopped
    ports:
      - "8081:80"
      - "444:443"
    volumes:
      - ./nginx/strategy-engine.nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - strategy-engine
    networks:
      - strategy-network

  mongo:
    image: mongo:latest
    container_name: panda-quant-strategy-mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    command: mongod --bind_ip_all --nojournal
    networks:
      - strategy-network

  redis:
    image: redis:latest
    container_name: panda-quant-strategy-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - strategy-network

volumes:
  mongo_data:
    driver: local
  redis_data:
    driver: local

networks:
  strategy-network:
    driver: bridge 