version: '3'
services:
  user-api:
    build:
      context: ../user-api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env
    networks:
      - panda-network
    depends_on:
      - mongodb
      - redis

  admin-api:
    build:
      context: ../admin-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - panda-network
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - panda-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - panda-network

networks:
  panda-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data: 