version: '3.8'

services:
  network-setup:
    image: alpine
    command: "true"
    networks:
      - panda-quant-network

networks:
  panda-quant-network:
    name: panda-quant-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1 