version: '3.8'

services:
  # Nginx 反向代理 (管理端)
  nginx-admin:
    image: nginx:alpine
    container_name: panda-quant-nginx-admin
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - panda-quant-network
    depends_on:
      - admin-api
      - admin-ui
    restart: unless-stopped

  # MongoDB 数据库
  mongodb:
    image: mongo:latest
    container_name: panda-quant-mongodb-admin
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=panda-quant
    volumes:
      - mongodb_admin_data:/data/db
    networks:
      - panda-quant-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis 缓存
  redis:
    image: redis:alpine
    container_name: panda-quant-redis-admin
    ports:
      - "6380:6379"
    volumes:
      - redis_admin_data:/data
    networks:
      - panda-quant-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 管理前端
  admin-ui:
    build:
      context: ../admin-ui
      dockerfile: Dockerfile
    container_name: panda-quant-admin-ui
    ports:
      - "3002:80"
    environment:
      - VITE_API_URL=https://pandatrade.space/api
    depends_on:
      admin-api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - panda-quant-network
    restart: unless-stopped

  # 管理后端
  admin-api:
    build:
      context: ../admin-api
      dockerfile: Dockerfile
    container_name: panda-quant-admin-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://admin:admin123@mongodb:27017/panda-quant?authSource=admin&retryWrites=true&w=majority
      - REDIS_URI=redis://redis:6379
      - JWT_SECRET=panda_quant_secret_key_2024
      - JWT_EXPIRES_IN=24h
    depends_on:
      - mongodb
      - redis
    networks:
      - panda-quant-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  panda-quant-network:
    driver: bridge

volumes:
  mongodb_admin_data:
  redis_admin_data: 