version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: panda-quant-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/letsencrypt:ro
      - ./admin-ui/dist:/usr/share/nginx/html/admin:ro
      - ./user-ui/dist:/usr/share/nginx/html:ro
    depends_on:
      - admin-api
      - user-api
      - admin-ui
      - user-ui
    restart: unless-stopped
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M

  admin-api:
    build:
      context: ../admin-api
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - NPM_CONFIG_CACHE=/tmp/.npm
    container_name: panda-quant-admin-api
    environment:
      - NODE_ENV=production
      - JWT_SECRET=Wl528586*
      - ENCRYPTION_KEY=Wl528586*
      - MONGODB_ADMIN_URI=mongodb://admin:Wl528586*@mongodb:27018/panda-quant-admin?authSource=admin
      - REDIS_ADMIN_URL=redis://:Wl528586*@redis:6380
    restart: unless-stopped
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1G

  user-api:
    build:
      context: ../user-api
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - NPM_CONFIG_CACHE=/tmp/.npm
    container_name: panda-quant-user-api
    environment:
      - NODE_ENV=production
      - JWT_SECRET=Wl528586*
      - ENCRYPTION_KEY=Wl528586*
      - MONGODB_USER_URI=mongodb://admin:Wl528586*@mongodb:27019/panda-quant-user?authSource=admin
      - REDIS_USER_URL=redis://:Wl528586*@redis:6381
    restart: unless-stopped
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1G

  admin-ui:
    build:
      context: ../admin-ui
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - NPM_CONFIG_CACHE=/tmp/.npm
    container_name: panda-quant-admin-ui
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://api.panda-quant.com/admin
    restart: unless-stopped
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1G

  user-ui:
    build:
      context: ../user-ui
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - NPM_CONFIG_CACHE=/tmp/.npm
    container_name: panda-quant-user-ui
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://api.panda-quant.com/user
    restart: unless-stopped
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1G

  frontend:
    image: panda-quant-frontend
    ports:
      - "80:80"
    networks:
      - panda-quant-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  mongodb:
    image: mongo:5.0
    container_name: panda-quant-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Wl528586*
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27018:27017"
      - "27019:27018"
    restart: unless-stopped
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 2G

  redis:
    image: redis:6.2-alpine
    container_name: panda-quant-redis
    command: redis-server --requirepass Wl528586*
    volumes:
      - redis_data:/data
    ports:
      - "6380:6379"
      - "6381:6380"
    restart: unless-stopped
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M

networks:
  panda-quant-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data: 