version: '3.8'

services:
  user-ui:
    build:
      context: ..
      dockerfile: docker/Dockerfile.user-ui
    container_name: panda-quant-user-ui
    restart: always
    networks:
      - panda-quant-network
    depends_on:
      - user-api

  user-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.user-api
    container_name: panda-quant-user-api
    restart: always
    networks:
      - panda-quant-network
    environment:
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/admin
      - REDIS_URI=redis://:${REDIS_PASSWORD}@redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    depends_on:
      - mongodb
      - redis

networks:
  panda-quant-network:
    external: true 