version: '3.8'

services:
  nginx-user:
    build:
      context: ../user-ui
      dockerfile: ../docker/Dockerfile.user-ui
    container_name: panda-quant-nginx-user
    ports:
      - "${USER_UI_PORT}:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  user-api:
    build:
      context: ../user-api
      dockerfile: ../docker/Dockerfile.user-api
    container_name: panda-quant-user-api
    ports:
      - "${USER_API_PORT}:3002"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_USER_URI}
      - REDIS_URL=${REDIS_USER_URL}
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    depends_on:
      - mongodb
      - redis
    restart: unless-stopped
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  user-ui:
    build:
      context: user-ui
      dockerfile: ../docker/Dockerfile.user-ui
    container_name: panda-quant-user-ui
    ports:
      - "3003:80"
    restart: unless-stopped
    networks:
      panda-quant-network:
        aliases:
          - user-ui
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  panda-quant-network:
    external: true 