version: '3.8'

services:
  # Nginx 反向代理
  nginx:
    image: nginx:alpine
    container_name: panda-quant-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - nginx_letsencrypt:/etc/letsencrypt
      - nginx_www:/var/www/html
    networks:
      - panda-quant-network
    depends_on:
      - admin-ui
      - admin-api
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # MongoDB 数据库
  mongodb-admin:
    image: mongo:latest
    container_name: panda-quant-mongodb-admin
    ports:
      - "27018:27017"  # MongoDB 管理端口
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=PandaQuant@2024
      - MONGO_INITDB_DATABASE=admin
    command: ["--auth"]
    volumes:
      - mongodb_admin_data:/data/db
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Redis 缓存
  redis-admin:
    image: redis:alpine
    container_name: panda-quant-redis-admin
    ports:
      - "6380:6379"  # Redis 管理端口
    command: ["redis-server", "--requirepass", "PandaQuant@2024"]
    volumes:
      - redis_admin_data:/data
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "PandaQuant@2024", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Admin API 服务
  admin-api:
    build:
      context: ../admin-api
      dockerfile: Dockerfile
    container_name: panda-quant-admin-api
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:PandaQuant@2024@mongodb-admin:27017/panda-quant-admin?authSource=admin
      - REDIS_URL=redis://:PandaQuant@2024@redis-admin:6379
      - JWT_SECRET=PandaQuant@2024
      - ENCRYPTION_KEY=PandaQuant@2024
    depends_on:
      - mongodb-admin
      - redis-admin
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Admin UI 服务
  admin-ui:
    build:
      context: ../admin-ui
      dockerfile: Dockerfile
    container_name: panda-quant-admin-ui
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=https://admin-api.pandatrade.space
    depends_on:
      - admin-api
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

networks:
  panda-quant-network:
    external: true

volumes:
  mongodb_admin_data:
  redis_admin_data:
  nginx_letsencrypt:
  nginx_www: 