version: '3.8'

services:
  nginx-admin:
    build:
      context: ../admin-ui
      dockerfile: ../docker/Dockerfile.admin-ui
    container_name: panda-quant-nginx-admin
    ports:
      - "${ADMIN_UI_PORT}:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  admin-api:
    build:
      context: ../admin-api
      dockerfile: ../docker/Dockerfile.admin-api
    container_name: panda-quant-admin-api
    ports:
      - "${ADMIN_API_PORT}:3001"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_ADMIN_URI}
      - REDIS_URL=${REDIS_ADMIN_URL}
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    depends_on:
      - mongodb
      - redis
    restart: unless-stopped
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb:
    image: mongo:latest
    container_name: panda-quant-mongodb
    ports:
      - "${MONGODB_ADMIN_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:latest
    container_name: panda-quant-redis
    ports:
      - "${REDIS_ADMIN_PORT}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb_data:
  redis_data:

networks:
  panda-quant-network:
    external: true 