version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: panda-quant-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/letsencrypt:ro
      - ./admin-ui/dist:/usr/share/nginx/html/admin:ro
      - ./user-ui/dist:/usr/share/nginx/html:ro
    depends_on:
      - admin-api
      - user-api
      - admin-ui
      - user-ui
    restart: unless-stopped
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  admin-api:
    build:
      context: .
      dockerfile: admin-api/Dockerfile
    container_name: panda-quant-admin-api
    environment:
      - NODE_ENV=production
      - JWT_SECRET=Wl528586*
      - ENCRYPTION_KEY=Wl528586*
      - MONGODB_ADMIN_URI=mongodb://admin:Wl528586*@mongodb:27018/panda-quant-admin?authSource=admin
      - REDIS_ADMIN_URL=redis://:Wl528586*@redis:6380
    restart: unless-stopped
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  user-api:
    build:
      context: .
      dockerfile: user-api/Dockerfile
    container_name: panda-quant-user-api
    environment:
      - NODE_ENV=production
      - JWT_SECRET=Wl528586*
      - ENCRYPTION_KEY=Wl528586*
      - MONGODB_USER_URI=mongodb://admin:Wl528586*@mongodb:27019/panda-quant-user?authSource=admin
      - REDIS_USER_URL=redis://:Wl528586*@redis:6381
    restart: unless-stopped
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  admin-ui:
    build:
      context: .
      dockerfile: admin-ui/Dockerfile
    container_name: panda-quant-admin-ui
    volumes:
      - ./admin-ui/dist:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3

  user-ui:
    build:
      context: .
      dockerfile: user-ui/Dockerfile
    container_name: panda-quant-user-ui
    volumes:
      - ./user-ui/dist:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: panda-quant-frontend
    ports:
      - "80:80"
    networks:
      - panda-quant-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Wl528586*
    volumes:
      - mongodb_data:/data/db
    networks:
      - panda-quant-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass Wl528586*
    volumes:
      - redis_data:/data
    networks:
      - panda-quant-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "Wl528586*", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  panda-quant-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data: 