version: '3.8'

services:
  network-setup:
    image: busybox
    command: "true"
    networks:
      - panda-quant-network

networks:
  panda-quant-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1 