version: '3.8'

services:
  # 用户前端
  user-ui:
    build:
      context: ../user-ui
      dockerfile: Dockerfile
    container_name: panda-quant-user-ui
    ports:
      - "3003:80"
    environment:
      - VITE_API_URL=http://user-api:3001
      - NODE_ENV=development
      - DEBUG=*
    networks:
      - panda-quant-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  panda-quant-network:
    external: true
    name: panda-quant-network

volumes:
  nginx_letsencrypt:
  nginx_www: 