services:
  nginx-user:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.user-ui
    container_name: panda-quant-nginx-user
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      panda-quant-network:
        aliases:
          - nginx-user
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  user-api:
    build:
      context: ../user-api
      dockerfile: ../deploy/Dockerfile.user-api
      args:
        - NODE_ENV=production
    container_name: panda-quant-user-api
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=Wl528586*
      - ENCRYPTION_KEY=Wl528586*
      - MONGODB_URI=mongodb://admin:Wl528586*@mongodb:27017/panda_quant
      - REDIS_URI=redis://:Wl528586*@redis:6379
    restart: unless-stopped
    networks:
      panda-quant-network:
        aliases:
          - user-api
    deploy:
      resources:
        limits:
          memory: 4G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  user-ui:
    build:
      context: ../user-ui
      dockerfile: ../deploy/Dockerfile.user-ui
    container_name: panda-quant-user-ui
    ports:
      - "3003:80"
    restart: unless-stopped
    networks:
      panda-quant-network:
        aliases:
          - user-ui
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  panda-quant-network:
    name: panda-quant-network
    external: true 