version: '3.8'

services:
  nginx-user:
    build:
      context: ../user-ui
      dockerfile: ../docker/Dockerfile.user-ui
    container_name: panda-quant-nginx-user
    ports:
      - "80:80"
    depends_on:
      - user-api
    networks:
      - panda-quant-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 3s
      retries: 3

  user-api:
    build:
      context: ../user-api
      dockerfile: ../docker/Dockerfile.user-api
    container_name: panda-quant-user-api
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb
      - redis
    networks:
      - panda-quant-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3002/health"]
      interval: 30s
      timeout: 3s
      retries: 3

  user-ui:
    build:
      context: ../user-ui
      dockerfile: ../docker/Dockerfile.user-ui
    container_name: panda-quant-user-ui
    ports:
      - "80:80"
    depends_on:
      - user-api
    networks:
      - panda-quant-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 3s
      retries: 3

networks:
  panda-quant-network:
    external: true 