version: '3.8'

services:
  # MongoDB 数据库
  mongodb:
    image: mongo:latest
    container_name: panda-quant-mongodb-user
    ports:
      - "27019:27017"  # MongoDB 用户端口
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=PandaQuant@2024
      - MONGO_INITDB_DATABASE=admin
    command: ["--auth"]
    volumes:
      - mongodb_user_data:/data/db
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Redis 缓存
  redis:
    image: redis:alpine
    container_name: panda-quant-redis-user
    ports:
      - "6381:6379"    # Redis 用户端口
    command: redis-server --requirepass PandaQuant@2024
    volumes:
      - redis_user_data:/data
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "PandaQuant@2024", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # 用户前端
  user-ui:
    build:
      context: ../user-ui
      dockerfile: Dockerfile
    image: deploy-user-ui
    container_name: panda-quant-user-ui
    ports:
      - "8082:80"      # User UI 访问端口
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://api.pandatrade.space
      - VITE_DOMAIN=pandatrade.space
      - VITE_API_SUBDOMAIN=api
    networks:
      - panda-quant-network
    depends_on:
      - user-api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # 用户后端
  user-api:
    build:
      context: ../user-api
      dockerfile: Dockerfile
    image: deploy-user-api
    container_name: panda-quant-user-api
    ports:
      - "8083:3000"    # User API 访问端口
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:PandaQuant@2024@mongodb:27019/panda-quant-user?authSource=admin
      - REDIS_URL=redis://:PandaQuant@2024@redis:6381
      - JWT_SECRET=Wl528586*
      - PORT=3000
      - DOMAIN=pandatrade.space
      - API_SUBDOMAIN=api
    networks:
      - panda-quant-network
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

networks:
  panda-quant-network:
    external: true

volumes:
  mongodb_user_data:
  redis_user_data:
  nginx_letsencrypt:
  nginx_www: 