version: '3.8'

services:
  # MongoDB 数据库
  mongodb:
    image: mongo:latest
    container_name: panda-quant-mongodb-user
    ports:
      - "27019:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis 缓存
  redis:
    image: redis:alpine
    container_name: panda-quant-redis-user
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 用户前端
  user-ui:
    build:
      context: ../user-ui
      dockerfile: Dockerfile
    image: deploy-user-ui
    container_name: panda-quant-user-ui
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://api.pandatrade.space
    networks:
      - panda-quant-network
    depends_on:
      - user-api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 用户后端
  user-api:
    build:
      context: ../user-api
      dockerfile: Dockerfile.api
    image: deploy-user-api
    container_name: panda-quant-user-api
    ports:
      - "3003:3001"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/panda-quant-user
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your_jwt_secret
      - API_PORT=3001
    networks:
      - panda-quant-network
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  panda-quant-network:
    name: panda-quant-network
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
  nginx_letsencrypt:
  nginx_www: 