version: '3.8'

services:
  # MongoDB 数据库
  mongodb:
    image: mongo:latest
    container_name: panda-quant-mongodb-user
    ports:
      - "27019:27017"
    volumes:
      - mongodb_user_data:/data/db
    networks:
      - panda-quant-network
    restart: always
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis 缓存
  redis:
    image: redis:alpine
    container_name: panda-quant-redis-user
    ports:
      - "6381:6379"
    volumes:
      - redis_user_data:/data
    networks:
      - panda-quant-network
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 用户前端
  user-ui:
    image: deploy-user-ui
    container_name: panda-quant-user-ui
    restart: always
    ports:
      - "3003:80"
    environment:
      - VITE_API_URL=http://pandatrade.space/api
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 用户后端
  user-api:
    image: deploy-user-api
    container_name: panda-quant-user-api
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/panda-quant
      - REDIS_URL=redis://redis:6379
      - CORS_ORIGIN=http://pandatrade.space
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  panda-quant-network:
    name: panda-quant-network
    driver: bridge

volumes:
  mongodb_user_data:
  redis_user_data:
  nginx_letsencrypt:
  nginx_www: 