version: '3.8'

services:
  nginx-admin:
    image: nginx:alpine
    container_name: panda-quant-nginx-admin
    ports:
      - "443:443"
    volumes:
      - ./nginx/admin.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/letsencrypt:ro
      - ./admin-ui/dist:/usr/share/nginx/html:ro
    depends_on:
      - admin-api
      - admin-ui
    restart: unless-stopped
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  admin-api:
    build:
      context: ../admin-api
      dockerfile: ../deploy/Dockerfile.admin-api
      args:
        - PORT=3001
    container_name: panda-quant-admin-api
    environment:
      - NODE_ENV=production
      - JWT_SECRET=Wl528586*
      - ENCRYPTION_KEY=Wl528586*
      - MONGODB_URI=mongodb://admin:Wl528586*@194.164.149.214:27017/panda_quant
      - REDIS_URI=redis://:Wl528586*@194.164.149.214:6379
    restart: unless-stopped
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  admin-ui:
    build:
      context: ../admin-ui
      dockerfile: ../deploy/Dockerfile.admin-ui
    container_name: panda-quant-admin-ui
    volumes:
      - ../admin-ui/dist:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb:
    image: mongo:latest
    container_name: panda-quant-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Wl528586*
      - MONGO_INITDB_DATABASE=panda_quant
    volumes:
      - mongodb_data:/data/db
    networks:
      - panda-quant-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:alpine
    container_name: panda-quant-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass Wl528586*
    volumes:
      - redis_data:/data
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  panda-quant-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

volumes:
  mongodb_data:
  redis_data: 