version: '3.8'

services:
  nginx-user:
    image: nginx:alpine
    container_name: panda-quant-nginx-user
    ports:
      - "81:80"
      - "444:443"
    volumes:
      - ./nginx/user.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/letsencrypt:ro
      - ./user-ui/dist:/usr/share/nginx/html:ro
    depends_on:
      - user-api
      - user-ui
    restart: unless-stopped
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  user-api:
    build:
      context: ../user-api
      dockerfile: ../deploy/Dockerfile.api
      args:
        - PORT=3002
    container_name: panda-quant-user-api
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - MONGODB_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/${MONGODB_DATABASE}
      - REDIS_URI=redis://:${REDIS_PASSWORD}@redis:6379
    restart: unless-stopped
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  user-ui:
    build:
      context: ../user-ui
      dockerfile: ../deploy/Dockerfile.ui
    container_name: panda-quant-user-ui
    volumes:
      - ../user-ui/dist:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  panda-quant-network:
    external: true 