version: "3.9"

services:
  user-api:
    build:
      context: ../user-api
    ports:
      - "4000:4000"
    env_file:
      - ../.env
    environment:
      - NODE_ENV=production
    networks:
      - panda-network
    depends_on:
      - mongodb
      - redis
    restart: always

  admin-api:
    build:
      context: ../admin-api
    ports:
      - "3000:3000"
    env_file:
      - ../.env
    environment:
      - NODE_ENV=production
    networks:
      - panda-network
    depends_on:
      - mongodb
      - redis
    restart: always

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - panda-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - panda-network

networks:
  panda-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data: 