version: '3.8'

services:
  # Nginx 反向代理 (用户端)
  nginx-user:
    image: nginx:alpine
    container_name: panda-quant-nginx-user
    ports:
      - "80:80"
    volumes:
      - ./nginx/user.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - panda-quant-network
    depends_on:
      user-ui:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # 用户前端
  user-ui:
    build:
      context: ../user-ui
      dockerfile: Dockerfile
    container_name: panda-quant-user-ui
    ports:
      - "3003:80"
    environment:
      - VITE_API_URL=http://user-api:3001
      - NODE_ENV=development
      - DEBUG=*
    networks:
      - panda-quant-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  panda-quant-network:
    external: true
    name: panda-quant-network

volumes:
  nginx_letsencrypt:
  nginx_www: 