version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/var/www/certbot:/var/www/certbot
    depends_on:
      - user-ui
      - user-api
      - admin-api
    restart: always

  user-ui:
    build:
      context: ../user-ui
      dockerfile: Dockerfile
    image: panda-quant-user-ui
    ports:
      - "3003:80"
    environment:
      - REACT_APP_API_URL=http://194.164.149.214:3000
      - REACT_APP_ADMIN_API_URL=http://194.164.149.214:3001
    restart: always

  user-api:
    build:
      context: ../user-api
      dockerfile: Dockerfile
    image: panda-quant-user-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/panda-quant
      - REDIS_URI=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
      - redis
    restart: always

  admin-api:
    build:
      context: ../admin-api
      dockerfile: Dockerfile
    image: panda-quant-admin-api
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/panda-quant
      - REDIS_URI=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
      - redis
    restart: always

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  mongodb_data:
  redis_data: 