version: '3.8'

services:
  # Nginx 反向代理 (用户端)
  nginx-user:
    image: nginx:alpine
    container_name: panda-quant-nginx-user
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/user.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/www:/var/www/certbot
    networks:
      - panda-quant-network
    depends_on:
      user-ui:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Certbot 用于 SSL 证书
  certbot-user:
    image: certbot/certbot
    container_name: panda-quant-certbot-user
    volumes:
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/www:/var/www/certbot
    networks:
      - panda-quant-network
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  # 用户前端
  user-ui:
    build:
      context: ../user-ui
      dockerfile: Dockerfile
    container_name: panda-quant-user-ui
    ports:
      - "3003:80"
    environment:
      - VITE_API_URL=http://user-api:3001
    networks:
      - panda-quant-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  panda-quant-network:
    external: true

volumes:
  nginx_letsencrypt:
  nginx_www: 