version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: panda-quant-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/letsencrypt:ro
      - ./admin-ui/dist:/usr/share/nginx/html/admin:ro
      - ./user-ui/dist:/usr/share/nginx/html:ro
    depends_on:
      - admin-api
      - user-api
    restart: unless-stopped
    networks:
      - panda-quant-network

  admin-api:
    build:
      context: ../admin-api
      dockerfile: Dockerfile
    container_name: panda-quant-admin-api
    environment:
      - NODE_ENV=production
      - MONGODB_ADMIN_URI=${MONGODB_ADMIN_URI}
      - REDIS_ADMIN_URL=${REDIS_ADMIN_URL}
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    restart: unless-stopped
    networks:
      - panda-quant-network

  user-api:
    build:
      context: ../user-api
      dockerfile: Dockerfile
    container_name: panda-quant-user-api
    environment:
      - NODE_ENV=production
      - MONGODB_USER_URI=${MONGODB_USER_URI}
      - REDIS_USER_URL=${REDIS_USER_URL}
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    restart: unless-stopped
    networks:
      - panda-quant-network

  admin-ui:
    build:
      context: ../admin-ui
      dockerfile: Dockerfile
    container_name: panda-quant-admin-ui
    volumes:
      - ./admin-ui/dist:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks:
      - panda-quant-network

  user-ui:
    build:
      context: ../user-ui
      dockerfile: Dockerfile
    container_name: panda-quant-user-ui
    volumes:
      - ./user-ui/dist:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks:
      - panda-quant-network

  frontend:
    image: panda-quant-frontend
    ports:
      - "80:80"
    networks:
      - panda-quant-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=PandaQuant@2024
    volumes:
      - mongodb_data:/data/db
    networks:
      - panda-quant-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - panda-quant-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  panda-quant-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data: 