version: '3.8'

services:
  nginx-admin:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.admin-ui
    container_name: panda-quant-nginx-admin
    ports:
      - "8081:80"
    restart: unless-stopped
    networks:
      panda-quant-network:
        aliases:
          - nginx-admin
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  admin-api:
    build:
      context: .
      dockerfile: Dockerfile.admin-api
      args:
        - NODE_ENV=production
    container_name: panda-quant-admin-api
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: unless-stopped
    networks:
      panda-quant-network:
        aliases:
          - admin-api
    deploy:
      resources:
        limits:
          memory: 4G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb:
    image: mongo:latest
    container_name: panda-quant-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Wl528586*
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      panda-quant-network:
        aliases:
          - mongodb
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:alpine
    container_name: panda-quant-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass Wl528586*
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      panda-quant-network:
        aliases:
          - redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb_data:
  redis_data:

networks:
  panda-quant-network:
    name: panda-quant-network
    external: true 