version: '3.8'

services:
  strategy-engine:
    build:
      context: ../strategy-engine
      dockerfile: ../docker/Dockerfile.strategy-engine
    container_name: panda-quant-strategy-engine
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_ADMIN_URI}
      - REDIS_URL=${REDIS_ADMIN_URL}
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    depends_on:
      - mongodb
      - redis
    restart: unless-stopped
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3004/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  server:
    build:
      context: ../server
      dockerfile: ../docker/Dockerfile.server
    container_name: panda-quant-server
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_ADMIN_URI}
      - REDIS_URL=${REDIS_ADMIN_URL}
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    depends_on:
      - mongodb
      - redis
    restart: unless-stopped
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  panda-quant-network:
    external: true 