version: "3.9"

services:
  user-api:
    build:
      context: ../user-api
    container_name: panda-quant-user-api
    ports:
      - "3001:3001"
    env_file:
      - ../.env
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/panda-quant
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRES_IN=7d
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=your_email@gmail.com
      - SMTP_PASS=your_app_password
      - FRONTEND_URL=http://localhost:3003
    networks:
      - panda-quant-network
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  admin-api:
    build:
      context: ../admin-api
    container_name: panda-quant-admin-api
    ports:
      - "3000:3000"
    env_file:
      - ../.env
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/panda-quant
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRES_IN=7d
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=your_email@gmail.com
      - SMTP_PASS=your_app_password
      - FRONTEND_URL=http://localhost:3002
    networks:
      - panda-quant-network
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  mongodb:
    image: mongo:latest
    container_name: panda-quant-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - panda-quant-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  redis:
    image: redis:alpine
    container_name: panda-quant-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - panda-quant-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  panda-quant-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data: 