services:
  nginx-user:
    image: nginx:alpine
    container_name: panda-quant-nginx-user
    ports:
      - "8080:80"
    volumes:
      - ./nginx/user.conf:/etc/nginx/nginx.conf:ro
      - ./user-ui/dist:/usr/share/nginx/html:ro
    depends_on:
      - user-api
      - user-ui
    restart: unless-stopped
    networks:
      panda-quant-network:
        aliases:
          - nginx-user
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  user-api:
    build:
      context: ../user-api
      dockerfile: Dockerfile
    container_name: panda-quant-user-api
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=Wl528586*
      - ENCRYPTION_KEY=Wl528586*
      - MONGODB_URI=mongodb://admin:Wl528586*@mongodb:27017/panda_quant
      - REDIS_URI=redis://:Wl528586*@redis:6379
    restart: unless-stopped
    networks:
      panda-quant-network:
        aliases:
          - user-api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  user-ui:
    build:
      context: ../user-ui
      dockerfile: Dockerfile
    container_name: panda-quant-user-ui
    ports:
      - "3003:3000"
    volumes:
      - ../user-ui/dist:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks:
      panda-quant-network:
        aliases:
          - user-ui
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  panda-quant-network:
    name: panda-quant-network 