version: '3.8'

services:
  # Nginx 反向代理 (用户端)
  nginx-user:
    image: nginx:alpine
    container_name: panda-quant-nginx-user
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/user.nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/user.conf.d:/etc/nginx/conf.d:ro
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/www:/var/www/certbot
    networks:
      - panda-network
    depends_on:
      - user-ui
    restart: unless-stopped

  # Certbot 用于 SSL 证书
  certbot-user:
    image: certbot/certbot
    container_name: panda-quant-certbot-user
    volumes:
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/www:/var/www/certbot
    networks:
      - panda-network
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  # 用户前端
  user-ui:
    build:
      context: ../user-ui
      dockerfile: Dockerfile
    container_name: panda-quant-user-ui
    ports:
      - "3003:80"
    environment:
      - VITE_API_URL=http://194.164.149.214:3001
    networks:
      - panda-network
    restart: unless-stopped

networks:
  panda-network:
    external: true
    name: deploy_panda-network

volumes:
  nginx_letsencrypt:
  nginx_www: 