version: '3.8'

x-healthcheck: &default-healthcheck
  interval: 30s
  timeout: 10s
  retries: 3

x-ui-resources: &ui-resources
  limits:
    cpus: '0.5'
    memory: 512M
  reservations:
    cpus: '0.1'
    memory: 128M

x-api-resources: &api-resources
  limits:
    cpus: '1'
    memory: 1G
  reservations:
    cpus: '0.2'
    memory: 256M

services:
  nginx:
    image: nginx:1.25.3
    container_name: panda-quant-nginx
    ports:
      - "${NGINX_PORT_HTTP}:80"
      - "${NGINX_PORT_HTTPS}:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - admin-api
      - user-api
      - admin-ui
      - user-ui
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      <<: *default-healthcheck
    deploy:
      resources: *ui-resources

  admin-api:
    image: panda-quant-admin-api:latest
    container_name: panda-quant-admin-api
    environment:
      - MONGODB_URI=${MONGODB_ADMIN_URI}
      - REDIS_URL=${REDIS_ADMIN_URL}
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    depends_on:
      - mongodb
      - redis
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      <<: *default-healthcheck
    deploy:
      resources: *api-resources

  user-api:
    image: panda-quant-user-api:latest
    container_name: panda-quant-user-api
    environment:
      - MONGODB_URI=${MONGODB_USER_URI}
      - REDIS_URL=${REDIS_USER_URL}
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    depends_on:
      - mongodb
      - redis
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      <<: *default-healthcheck
    deploy:
      resources: *api-resources

  admin-ui:
    image: panda-quant-admin-ui:latest
    container_name: panda-quant-admin-ui
    environment:
      - API_URL=${ADMIN_API_URL}
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083"]
      <<: *default-healthcheck
    deploy:
      resources: *ui-resources

  user-ui:
    image: panda-quant-user-ui:latest
    container_name: panda-quant-user-ui
    environment:
      - API_URL=${USER_API_URL}
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084"]
      <<: *default-healthcheck
    deploy:
      resources: *ui-resources

  mongodb:
    image: mongo:6.0
    container_name: panda-quant-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - "${MONGODB_ADMIN_PORT}:27017"
      - "${MONGODB_USER_PORT}:27018"
    volumes:
      - mongodb_data:/data/db
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      <<: *default-healthcheck
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 1G

  redis:
    image: redis:7.0
    container_name: panda-quant-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_ADMIN_PORT}:6379"
      - "${REDIS_USER_PORT}:6380"
    volumes:
      - redis_data:/data
    networks:
      - panda-quant-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      <<: *default-healthcheck
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.2'
          memory: 512M

networks:
  panda-quant-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data: 