version: '3'
services:
  user-ui:
    build:
      context: ../user-ui
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
    networks:
      - panda-network
    depends_on:
      - user-api

  admin-ui:
    build:
      context: ../admin-ui
      dockerfile: Dockerfile
    ports:
      - "81:80"
    env_file:
      - .env
    networks:
      - panda-network
    depends_on:
      - admin-api

networks:
  panda-network:
    driver: bridge 